version: '3.8'

services:
  app:
    build: .
    container_name: messaging_app
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://postgres:postgres@db:5432/messaging?sslmode=disable
      - REDIS_URL=redis://redis:6379/0
      - WEBHOOK_URL=https://webhook.site/4c65e618-2eb0-4f70-8787-3bc8681395eb
      - AUTH_KEY=INS.me1x9uMcyYGlhKKQVPoc.bO3j9aZwRTOcA2Ywo
      - MAX_CONTENT_LENGTH=160
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: postgres:14
    container_name: messaging_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=messaging
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: messaging_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
